### ISSUE TITLE
Current master of fv3gfs-fortran breaks componetwise physics tendency getters

### ISSUE THREAD

**Issue by nbren12** [VulcanClimateModeling/fv3gfs-wrapper#230]
I noticed that the new fv3gfs-fortran master breaks the fv3net master: https://github.com/VulcanClimateModeling/fv3net/pull/953

This happens because https://github.com/VulcanClimateModeling/fv3gfs-fortran/commit/d2f59ffd9cc091131f9f05fac5a6126ac85af0d9 moved these physics tendency diagnostics into the same diagnostics manager as the dynamical core diagnostics, breaking backwards compatibility.

This is the error message:
```
ValueError: There is no diagnostic tendency_of_specific_humidity_due_to_microphysics in module gfs_phys.
```

Perhaps catching this kind of error sooner is a good motivation for moving more of the fv3gfs-wrapper code into fv3gfs-fortran. I'm not sure if the wrapper tests try and grab this data or not.

cc @spencerkclark

**Comment by spencerkclark** [comment]
Right...I should have remembered the dependence on these.  I think there is a way to maintain backwards compatibility for these from the fortran side.  I'll see what I can do.

It looks like the [tests in the wrapper](https://github.com/VulcanClimateModeling/fv3gfs-wrapper/blob/40ec7ab7103f193642771b32387b47a1c4cabc58/tests/test_diagnostics.py#L36-L47) would have caught this, but we just haven't updated the fortran source yet.  I agree it would have been nice to somehow have been reminded about this automatically when writing the PR to the fortran model; it could take some work for that though.

**Comment by nbren12** [comment]
Don't worry, I think these kinds of things are unavoidable as long as fv3gfs-wrapper deeply accesses the internal data structures of the model. Would it be worth adding a getter for the regular diagnostics here?
