### ISSUE TITLE
Should the location of the cached data be considered "public API"?

### ISSUE THREAD

**Issue by nbren12** [VulcanClimateModeling/fv3gfs-wrapper#94]
The tests of fv3net currently refer to the location of the cached data by absolute path. See this example:
https://github.com/VulcanClimateModeling/fv3net/blob/1025f7caf41599cd9310851936e9f395269d9e4f/workflows/prognostic_c48_run/tests/test_regression.py#L22
Notice that the strange path is used because fv3gfs-python:v0.4.3 stored it's data at the incorrect path. This issue led to an integration failure (which I knew would happen) when we bumped to current version of fv3gfs-python (which has a correct version of the path).

My question is, should this location be considered a "public API" of the fv3gfs-python docker image or is it an implementation detail of `fv3config`? 

If it is public API, then can we formalize this by adding an  `ENV FV3CONFIG_CACHE=...` to the dockerfile here, and referring to the environment variable in external repository?

If it is not public API, we should refactor our tests to only use fv3config to mediate all interactions with this cache.

OR...should we remove this cache altogether, which seems like a common source of integration problems, and require that the downstream tests provision their own data (e.g. using fv3config)? I see some advantages of this approach in terms of simplicity.

**Comment by mcgibbon** [comment]
Closing this issue since the original question seems to be answered and we have no planned action items.
